spring.application.name=pcshop
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://localhost:3306/godagamaPCzone?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=chathura
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

cloudinary.cloud-name=dau59mvx0
cloudinary.api-key=691435665269355
cloudinary.api-secret=Nz6-awuewtxM1tv5C_7br-UPhrc